import { Toaster } from "@/components/ui/sonner"
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TeamUp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider >
      <html lang="en">
        <link rel="shortcut icon" href="./favicon.ico" />
        <body className={
          `${inter.className}`
        }>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark">
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
